CREATE TABLE IF NOT EXISTS goods (
  id INT(11) NOT NULL AUTO_INCREMENT,
  title VARCHAR(45) DEFAULT NULL,
  `desc` VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS tasks (
  task_id INT(11) NOT NULL AUTO_INCREMENT,
  subject VARCHAR(45) DEFAULT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  description VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (task_id)
) ENGINE=InnoDB;
ALTER TABLE goods ADD COLUMN `myphone1` varchar(255) DEFAULT NULL AFTER `myphone`;
ALTER TABLE `goods` ADD COLUMN `myphone1`  varchar(255) NULL AFTER `myphone`;